// let a = "i am a student";
// let b = a + " " + " " + ".";
// let c = a.split(" ").join(" " + " ");
// let d = a.trim();
// console.log(a, d);
// console.log(a.length - a.trim().length);
// console.log(b);
// console.log(c);
// console.log(14 % 3, parseInt(14 / 3));
// console.log(/^[A-Z]$/i.test("d"));
// console.log(a.slice(0, 3));
// console.log(a);
let a = "am2";
console.log(parseInt(a.charAt(a.length - 1)));
